apiVersion: v1
kind: Secret
metadata:
  name: quantumdx-secrets
  namespace: quantumdx
type: Opaque
stringData:
  SQLSERVER_CONN_STR: "REPLACE_ME"
  VAULT_ADDR: "REPLACE_ME"
  VAULT_TOKEN: "REPLACE_ME"
